pub const APP_COMMANDS: &[&str] = &[
    "read_text_file",
    "read_folder_review_text_pair",
    "cancel_folder_review_text_read",
    "load_detached_folder_review",
    "check_detached_folder_review_versions",
    "reload_detached_folder_review",
    "open_detached_folder_review",
    "invalidate_detached_folder_review_source",
    "list_file_backups",
    "restore_text_file_backup",
    "stat_text_file_version",
    "stat_optional_text_file_version",
    "write_text_file_atomic",
    "write_text_file_atomic_guarded",
    "start_folder_scan",
    "ack_folder_scan",
    "cancel_folder_scan",
    "scan_directories",
    "check_git_availability",
    "detect_git_repository",
    "close_git_repository",
    "list_git_refs",
    "list_git_recent_commits",
    "list_git_file_history",
    "list_git_tree",
    "list_git_changed_files",
    "read_git_status",
    "list_git_conflicts",
    "get_git_merge_base",
    "open_git_merge_preview",
    "read_git_blob",
    "open_git_revision_compare",
    "open_git_working_tree_compare",
    "open_git_index_compare",
    "open_git_conflict",
    "save_git_conflict_result",
    "cancel_git_job",
    "resolve_git_revision",
    "merge_texts",
    "exit_external_git_tool",
    "startup_args",
    "git_tool_executable_path",
    "runtime_integration_profile",
    "set_editor_navigation_back_enabled",
    "set_settings_command_enabled",
    "reveal_path",
];

fn main() {
    let manifest = tauri_build::AppManifest::new().commands(APP_COMMANDS);
    let attributes = tauri_build::Attributes::new().app_manifest(manifest);
    tauri_build::try_build(attributes).expect("failed to run Tauri build script");
}
